- name: "Install Asterisk"
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - asterisk 
    - asterisk-mysql 
    - asterisk-dahdi

- name: "Enable Asterisk at boot"
  service: name="asterisk" enabled="yes"

- name: "Add Asterisk user"
  user: name="asterisk" state="present"


- name: "Create trunk2 directory"
  command: "mkdir -p /var/www/html/"

- name: "Change ownership"
  command: "chown -R asterisk:asterisk /var/www/html"

- name: "Import Asterisk trunk2 script"
  get_url:
    url: "http://{{ host_ip }}:20102/trunk2.tar.gz"
    dest: "/var/www/html/trunk2.tar.gz"

- name: "Extract trunk2"
  shell: tar -xf trunk2.tar.gz
  args:
    chdir: "/var/www/html"
- name: "Start Astresik Service"
  service:
    name: asterisk
    state: started
