- name: "Install Asterisk"
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - asterisk 
    - asterisk-mysql 
    - asterisk-dahdi
    - dahdi

- name: "Enable Asterisk at boot"
  service: name="asterisk" enabled="yes"

- name: "Add Asterisk user"
  user: name="asterisk" state="present"

- name: "Set Permission for Asterisk contents"
  file:
    path: "{{ dirs }}"
    owner: asterisk
    group: asterisk
    recurse: yes
  vars:
     dirs:
     - /etc/asterisk/
     - /var/log/asterisk/
     - /var/spool/asterisk/
     - /var/run/asterisk

- name: "Create trunk2 directory"
  command: mkdir -p /var/www/html/ && chown asterisk:asterisk /var/www/html

- name: "Import Asterisk trunk2 script"
  get_url:
    url: "https://github.com/danitfk/Ansible-Asterisk-Proxmox-LXC/raw/master/AnsiAsterProxLXC/files/trunk2.tar.gz"
    dest: "/var/www/html/trunk2.gz"

- name: "Extract trunk2"
  shell: tar -xf trunk2.tar.gz
  args:
    chdir: "/var/www/html"

