- name: "Install Asterisk 11.17.1 Release"
  yum: name="https://packages.asterisk.org/centos/6/asterisk-11/x86_64/RPMS/asterisk-11.17.1-1_centos6.x86_64.rpm" state="present"
  
- name: "Install Asterisk Addons 11.17.1 Release"
  yum: name="https://packages.asterisk.org/centos/6/asterisk-11/x86_64/RPMS/asterisk-addons-11.17.1-1_centos6.x86_64.rpm" state="present"

- name: "Install Asterisk MySQL 11.17.1 Release"
  yum: name="https://packages.asterisk.org/centos/6/asterisk-11/x86_64/RPMS/asterisk-addons-mysql-11.17.1-1_centos6.x86_64.rpm" state="presenet"

- name: "Install Asterisk Dahdi 11.17.1 Release"
  yum: name="https://packages.asterisk.org/centos/6/asterisk-11/x86_64/RPMS/asterisk-dahdi-11.17.1-1_centos6.x86_64.rpm" state="present"

- name: "Install Asterisk MySQL 11.17.1 Release"
  yum: name="" state="present"

- name: "Install Asterisk Development 11.17.1 Release"
  yum: name="https://packages.asterisk.org/centos/6/asterisk-11/x86_64/RPMS/asterisk-devel-11.17.1-1_centos6.x86_64.rpm" state="present"


- name: "Enable Asterisk at boot"
  service: name="asterisk" enabled="yes"

- name: "Add Asterisk user"
  user: name="asterisk" state="present"


- name: "Create trunk2 directory"
  command: "mkdir -p /var/www/html/"

- name: "Change ownership"
  command: "chown -R asterisk:asterisk /var/www/html"

- name: "Import Asterisk trunk2 script"
  get_url:
    url: "http://{{ prox_host_ip }}:20102/trunk2.tar.gz"
    dest: "/var/www/html/trunk2.tar.gz"

- name: "Extract trunk2"
  shell: tar -xf trunk2.tar.gz
  args:
    chdir: "/var/www/html"
- name: "Start Astresik Service"
  service:
    name: asterisk
    state: started
